### ISSUE TITLE
Weird resulted images using line_profiler and tamppa

### ISSUE THREAD

**Issue by alisheikholeslam** [pra-dan/TAMPPA#3]
I have a problem showing the results on the mentioned [Colab link](https://colab.research.google.com/drive/1yL6vdPSnx_NQQ9-eRFQ9u4TkPWHbwZXK?usp=sharing) on my [ex issue](https://github.com/pra-dan/TAMPPA/issues/2). I have tested it once by using [your written method](https://github.com/pyutils/line_profiler/issues/117#issuecomment-1019808659) getting output without using console directly, once by using console directly, and once by `subprocess.getoutput("python -m memory_profiler test.py > mem_res.txt")`; `subprocess` gets same result, but with one additional outputted image.
As it is shown on the resulted image, the lines are weird and is not true.
![image](https://user-images.githubusercontent.com/63285654/150868718-75cff559-ba42-40a9-ad35-27b3fe438fb5.png)
The outputted `mem_res.txt` seems to be without any problem:

![err](https://user-images.githubusercontent.com/63285654/151107749-a84ecc87-173f-41b6-b045-b337fe4e4e49.PNG)

**Do you have any idea why the line numbers are weird and what is differences between two resulted images using `subprocess`?**

I have some guesses on it:
1) sorting behavior in [line_profiler](https://github.com/pyutils/line_profiler/blob/5994c08bec2e4845a2b74d6c5f2d5c9b526f696f/line_profiler/line_profiler.py#L242)
2) functions' defining style on my python written code
3) frequent calling of `index` function (the weakest probability)!

If I use `@profile` decorator from `memory_profiler` just above the two functions named `operation_` and `elapses`, the results will be shown in an acceptable shape (**_as a suggestion, it is better to show lines' numbers (horizontal axis) as integers_**):
![myplot](https://user-images.githubusercontent.com/63285654/151109922-84ec9e91-9413-413a-be8f-02fd8b0331e7.png)
![ss](https://user-images.githubusercontent.com/63285654/151109929-825acb27-365d-4fc2-a65d-c5c92b8755ae.PNG)

**Comment by pra-dan** [comment]
That's unexpected. Let me have a look, will get back to you soon.

**Comment by pra-dan** [comment]
Can you share the code (along with the sample data) you have been using ? if its not proprietary .... 
Also, can you confirm if the `mem_parse` works fine when using `@profiler` decorator ?

**Comment by alisheikholeslam** [comment]
> Can you share the code (along with the sample data) you have been using ? if its not proprietary .... Also, can you confirm if the `mem_parse` works fine when using `@profiler` decorator ?

Codes are in the aforementioned [Colab link](https://colab.research.google.com/drive/1yL6vdPSnx_NQQ9-eRFQ9u4TkPWHbwZXK?usp=sharing) and [sample data link](https://drive.google.com/file/d/14RJ0Ackx88NzQWloops5FagzuNQYDSrh/view?usp=sharing) are mentioned in that for download. Do you mean writing them here (it is ok) or anything else?
As I have mentioned before for `@profiler`

> the results will be shown in an acceptable shape

I don't know if that shows the true results but the output are shown in an acceptable form.
I will prepare the codes here, too, if it is needed.

**Comment by alisheikholeslam** [comment]
> Can you share the code (along with the sample data) you have been using ? if its not proprietary .... Also, can you confirm if the `mem_parse` works fine when using `@profiler` decorator ?

Codes are in the aforementioned [Colab link](https://colab.research.google.com/drive/1yL6vdPSnx_NQQ9-eRFQ9u4TkPWHbwZXK?usp=sharing) and [sample data link](https://drive.google.com/file/d/14RJ0Ackx88NzQWloops5FagzuNQYDSrh/view?usp=sharing) are mentioned in that for download. Do you mean writing them here (it is ok) or anything else?
As I have mentioned before for `@profiler`

> the results will be shown in an acceptable shape

I don't know if that shows the true results but the output are shown in an acceptable form.

tamp.py:
```
import subprocess
import numpy as np

from line_profiler import LineProfiler, show_text, load_stats
# from memory_profiler import profile       # --------------------------> must be activated for profile decorator method
from tamppa import mem_parse


a = np.load('a.npy')
b = np.load('b.npy')
c = np.load('c.npy')
d = np.load('d.npy')
e = np.load('e.npy')


def inbox_(pnt, pol):

    ll = np.amin(pol, axis=0)
    ur = np.amax(pol, axis=0)

    in_idx = np.all(np.logical_and(ll <= pnt, pnt < ur), axis=1)

    return in_idx


# @profile()                                # --------------------------> must be activated for profile decorator method
def operation_(a, b, c):

    r_active = np.take(a, c)
    r_add = np.add.reduce(r_active, axis=1)
    paired_cent_dis = np.sum((r_add, b), axis=0)

    return np.power(b, 2) * np.power(paired_cent_dis, 2)


# @profile()                                # --------------------------> must be activated for profile decorator method
def elapses(a, b, c, d, e):
    if len(b) > 0:
        elaps = np.empty([len(d), ], dtype=object)
        operate_ = operation_(a, b, c)

        for i, j in enumerate(d):
            in_bool = inbox_(e, j)
            elaps[i] = np.sum(operate_[in_bool])
            operate_ = operate_[np.invert(in_bool)]
            e = e[np.invert(in_bool)]

        return elaps


# elapses(a, b, c, d, e)                    # --------------------------> must be activated for profile decorator method
# """
# ---------------------------------- must be deactivated for profile decorator method ----------------------------------
lp = LineProfiler()
lp.add_function(inbox_)
lp.add_function(operation_)
lp_wrapper = lp(elapses)
lp_wrapper(a, b, c, d, e)
lp.print_stats()
# ----------------------------------------------------------------------------------------------------------------------
# """
subprocess.getoutput("python -m memory_profiler tamp.py > mem_res.txt")
mem_parse('mem_res.txt')

```
[tamp file and sample data.zip](https://github.com/pra-dan/TAMPPA/files/8020561/tamp.file.and.sample.data.zip)

***Note:** This code will get some different results due to some changes in that.*

**Comment by pra-dan** [comment]
Hi Ali, I saw the `tamp.py` file and I think I know the answer to your question:
> Do you have any idea why the line numbers are weird and what is differences between two resulted images using subprocess?

I am looking to the random line-numbers but regarding the extra plot popping up while using `subprocess`, its probably because you are running the `tamp.py` file twice recursively. This is because you run `subprocess` inside the `tamp.py` while it should be used separatedly (like in another file).

**Comment by pra-dan** [comment]
@alisheikholeslam I have committed some changes. Please uninstall the package and then run 
```console
git clone https://github.com/pra-dan/TAMPPA.git
git checkout 0.1
```

**Comment by pra-dan** [comment]
I will close this issue if resolved.

**Comment by alisheikholeslam** [comment]
> I will close this issue if resolved.

Did you test it by my prepared data and python file and get the correct shape? It have uninstalled the previous Tamppa package and cloned the file as you said. Then I went to tamppa folder directory from pycharm terminal and ran `git checkout 0.1` there:
```
Note: switching to '0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 1e8a5f5 Add v1.0
```
Then I tried to install it by `python -m setup.py install`, which get error for repeated "version" in the `setup.py`:
```
  File "setup.py", line 12
    version="0.0.1",
    ^
SyntaxError: keyword argument repeated
```
I commented the second version line and it was installed without any error. I wrote these steps to check if there is any mistake from me. But, I got the same result for the prepared file and data.
How could I uninstall it and reinstall again now? I have installed it using pip before and uninstalled it by `python -m pip uninstall tamppa`, but now I install it using setup.py … and I can not uninstall.

**Comment by pra-dan** [comment]
Hi @alisheikholeslam Yes I did test it on your dataset using the same files you provided. I got desired results. 
After uninstalling using `pip`, try running
```console
$ git clone https://github.com/pra-dan/TAMPPA.git
$ git checkout 0.1
$ pip3 install -e TAMPPA
```
Before using TAMPPA, always ensure its version by using
```python3
import tamppa as tp
print(tp.__version__)
```

---
Also I suggest using a virtualenv or a conda environment if different versions cause a problem.

**Comment by alisheikholeslam** [comment]
> ```python
> import tamppa as tp
> print(tp.__version__)
> ```

shows: `0+untagged.21.g1e8a5f5.dirty`

I could not check the results yet. I doubt if it is the last file on your repository which you have tested because, as I mentioned, `setup.py` have an error in it: *version* is repeated.

I try to check it again by commenting the second version line in the `setup.py` and now I am getting the following error (*installed pandas version is 1.4.1*):
```
Traceback (most recent call last):
  File "C:\Users\Ali\anaconda3\envs\test\lib\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-4acc3f5ee847>", line 1, in <module>
    mem_parse('mem_res.txt')
  File "c:\users\ali\tamppa\tamppa\tamppa_code_mem.py", line 146, in mem_parse
    decode()
  File "c:\users\ali\tamppa\tamppa\tamppa_code_mem.py", line 127, in decode
    mbs_float = df["Mem usage"].str.split(' ',expand=True)[0].astype(np.float)
  File "C:\Users\Ali\anaconda3\envs\test\lib\site-packages\pandas\core\generic.py", line 5920, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\Ali\anaconda3\envs\test\lib\site-packages\pandas\core\internals\managers.py", line 419, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\Ali\anaconda3\envs\test\lib\site-packages\pandas\core\internals\managers.py", line 304, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\Ali\anaconda3\envs\test\lib\site-packages\pandas\core\internals\blocks.py", line 580, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\Ali\anaconda3\envs\test\lib\site-packages\pandas\core\dtypes\cast.py", line 1292, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\Ali\anaconda3\envs\test\lib\site-packages\pandas\core\dtypes\cast.py", line 1237, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\Ali\anaconda3\envs\test\lib\site-packages\pandas\core\dtypes\cast.py", line 1181, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 'time:'
```
I have installed line-profiler 2.1.2 using conda (there is not 2.1.1 on anaconda) and removed line `line-profiler==2.1.1` in `requirements.txt`; I don't think the error be related to this.
